---

# List of iptables INPUT rules to manage, many variables can be found in
# template files, located in templates/etc/ferm/filter-input.d/ directory.
# Additional variables are described below.

# Required:
  # item.dport		list of destination ports to configure

ferm_ansible_controllers: ['84.39.225.34']

# Optional:
  # item.protocol		list of protocols to configure (tcp, udp)
  # item.saddr		list of source addresses to accept
  # item.accept_any	accept connections from any IP address if True
  # item.disabled		if True, disable the rule (can be used to toggle rule via variable)
  # item.enabled		if True, enable the rule (can be used to toggle rule via variable)
  
ferm_input_list:
  - type: 'dport_accept'
    protocol: tcp
    dport: ['http', 'https', 'smtp']
